name: books-library
version : "3.9"

services:
  db:
    build: 
      context: ./database
      dockerfile: .dockerfile
    container_name: postgres_ctr
    restart: unless-stopped
    
    env_file: 
      - ./database/.env
    ports: 
      - 5012:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  backend:
    build: 
      context: ./backend
      dockerfile: .dockerfile
    container_name: backend_ctr
    restart: unless-stopped
    
    env_file: 
      - ./backend/.env
    ports: 
      - 5013:5013
    networks:
      - app_network
    depends_on:
      - db
  api-services:
    build: 
      context: ./api-services
      dockerfile: .dockerfile
    container_name: api-services_ctr
    restart: unless-stopped
    
    env_file: 
      - ./api-services/.env
    ports: 
      - 5014:5014
    networks:
      - app_network
    depends_on:
      - backend
      - db

networks:
  app_network:
    driver: bridge


volumes: 
  postgres_data:
